apiVersion: v1
kind: Service
metadata:
  labels:
    app: mongodb
  name: mongodb
spec:
  ports:
  - port: 27017
    protocol: TCP
    targetPort: 27017
  selector:
    app: mongodb
  type: ClusterIP
status:
  loadBalancer: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  labels:
    app: mongodb
spec:
  selector:
    matchLabels:
      app: mongodb
  replicas: 1
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - image: tutum/mongodb
        name: mongodb
        env:
        - name: AUTH
          value: "no"
        - name: MONGO_DATA_DIR
          value: "/data/db"
        - name: MONGO_LOG_DIR
          value: "/dev/null"
        ports:
        - containerPort: 27017
        volumeMounts:
        - name: shared-data
          mountPath: /data/db
      volumes:
      - name: shared-data
        persistentVolumeClaim:
          claimName: nfs-pvc1
